run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/xlip/multistream

issues:
  exclude-dirs:
    - dist
    - bin
