version: "2"
linters:
  enable:
    - misspell
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - dist
      - bin
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/xlip/multistream
  exclusions:
    generated: lax
    paths:
      - dist
      - bin
      - third_party$
      - builtin$
      - examples$
